[output]
# If disabled, the path in presets are directly applied, relative or absolute
# If enabled, the paths in presets must be relative
use-root = true
# Can be relative or absolute
out-root = "out"


[[Presets]]
name = "Main"
include-flags = ["neuro", "evil", "duet"]
exclude-flags = ["v1", "v2", "duplicate"]
# From root
path = "main"

[[Presets]]
name = "Old"
include-flags = ["v1", "v2"]
exclude-flags = ["duplicates"]
# From root
path = "v1v2"

[[Presets]]
name = "Duplicates"
include-flags = ["duplicate"]
exclude-flags = []
# From root
path = "duplicates"


# Other examples of presets
# [[Presets]]
# #v3 only
# name = "Neuro"
# include-flags = ["neuro"]
# exclude-flags = ["duet", "evil", "v1", "v2", "duplicate"]
# # From root
# path = "neuro"

# [[Presets]]
# name = "Evil"
# include-flags = ["evil"]
# exclude-flags = ["duet", "neuro", "v1", "v2", "duplicate"]
# # From root
# path = "evil"

# [[Presets]]
# name = "Duets"
# include-flags = ["duet"]
# exclude-flags = ["v1", "v2", "duplicate"]
# # From root
# path = "duets"
