[output]
# If disabled, the path in presets are directly applied, relative or absolute
# If enabled, the paths in presets must be relative
use-root = true
# Can be relative or absolute
out-root = "out"

[features]
# Needs mp3gain installed and accessible via the path
activated = ["mp3gain"]

[features.mp3gain]
# Runs mp3 gain on all files from a preset, it averages the gain over all files for a smoother experience.
# Warning: It can take a long time !
# Modes are "per-preset" | "on-all"
# Per-preset needs to have a boolean on each preset to know if mp3gain is ran
# On-all just bypasses the boolean, doesn't check for its existence, activates mp3gain for all
activation = "per-preset"

[[Presets]]
name = "Main"
include-flags = ["duet", "evil", "neuro"]
exclude-flags = ["duplicate", "v1", "v2"]
# From root
path = "main"
mp3gain = true

[[Presets]]
name = "Old"
include-flags = ["v1", "v2"]
exclude-flags = ["duplicates"]
# From root
path = "v1v2"
mp3gain = true

[[Presets]]
name = "Duplicates"
include-flags = ["duplicate"]
exclude-flags = []
# From root
path = "duplicates"
mp3gain = false


# Other examples of presets
# [[Presets]]
# #v3 only
# name = "Neuro"
# include-flags = ["neuro"]
# exclude-flags = ["duet", "evil", "v1", "v2", "duplicate"]
# # From root
# path = "neuro"

# [[Presets]]
# name = "Evil"
# include-flags = ["evil"]
# exclude-flags = ["duet", "neuro", "v1", "v2", "duplicate"]
# # From root
# path = "evil"

# [[Presets]]
# name = "Duets"
# include-flags = ["duet"]
# exclude-flags = ["v1", "v2", "duplicate"]
# # From root
# path = "duets"
